Document: subsurface-dfx-repo-keyring
Title: Debian subsurface-dfx-repo-keyring Manual
Author: <insert document author here>
Abstract: This manual describes what subsurface-dfx-repo-keyring is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/subsurface-dfx-repo-keyring/subsurface-dfx-repo-keyring.sgml.gz

Format: postscript
Files: /usr/share/doc/subsurface-dfx-repo-keyring/subsurface-dfx-repo-keyring.ps.gz

Format: text
Files: /usr/share/doc/subsurface-dfx-repo-keyring/subsurface-dfx-repo-keyring.text.gz

Format: HTML
Index: /usr/share/doc/subsurface-dfx-repo-keyring/html/index.html
Files: /usr/share/doc/subsurface-dfx-repo-keyring/html/*.html
