#!/bin/bash

set -e
set -x

test -d "$SUBSURFACE_DEBIAN_SRCDIR"

if test -z "$VERSION"; then
	VERSION=$(date +%Y%m%d%H%M)
fi

git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/subsurface.git

if test -n "$THIS_BUILD_ID"; then
	pushd subsurface

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	popd
fi

pushd subsurface
./scripts/get-version.sh 1 > .latest-subsurface-buildnumber
mv -f .latest-subsurface-buildnumber latest-subsurface-buildnumber
echo dfx > latest-subsurface-buildnumber-extension
qlitehtml=$(grep ^CURRENT_QLITEHTML= scripts/get-dep-lib.sh | cut -d= -f2 | sed 's/"//g')
popd

git clone \
	--branch qt6-upstream \
	--depth 1 \
	--single-branch \
	--recurse-submodules \
	--shallow-submodules \
	https://github.com/subsurface/googlemaps.git googlemaps-qt6
pushd googlemaps-qt6
rm -rf .git
popd

git clone \
	--revision f32bfdb8887943f3f0b7ea32ef57c0ebec5683aa \
	--depth 1 \
	--single-branch \
	--recurse-submodules \
	--shallow-submodules \
	https://github.com/qt/qtlocation.git qtlocation-qt6
pushd qtlocation-qt6
rm -rf .git
popd

git clone \
	--revision "$qlitehtml" \
	--depth 1 \
	--single-branch \
	--recurse-submodules \
	--shallow-submodules \
	https://github.com/dirkhh/qlitehtml.git
pushd qlitehtml
rm -rf src/3rdparty/litehtml/.git
rm -rf .git
popd

git clone https://github.com/cschramm/irda.git
test -d irda

test ! -e subsurface-qt6-beta-"$VERSION"
mkdir subsurface-qt6-beta-"$VERSION"

rm -rf subsurface/.github
rm -rf subsurface/.git
rm -rf subsurface/libdivecomputer/.github
rm -rf subsurface/libdivecomputer/.git
rm -rf qtlocation/.git
rm -rf irda/.git

cp -va subsurface/. subsurface-qt6-beta-"$VERSION"
cp -va googlemaps-qt6 subsurface-qt6-beta-"$VERSION"/googlemaps-qt6
cp -va qlitehtml subsurface-beta-"$VERSION"/qlitehtml
cp -va qtlocation-qt6 subsurface-qt6-beta-"$VERSION"/qtlocation-qt6
cp -va irda subsurface-qt6-beta-"$VERSION"/irda
tar -czf subsurface-qt6-beta_"$VERSION".orig.tar.gz subsurface-qt6-beta-"$VERSION"
rm -rf subsurface googlemaps-ssrf googlemaps-qt6 qtlocation qtlocation-qt6 qtpositioning irda qlitehtml

echo export VERSION="$VERSION"
