#!/bin/bash

set -e

test -n "$RELEASE"

SRCDIR=~/src

VERSION=5.0.1
BRANCH=v$VERSION

test -f ../subsurface_"$VERSION".orig.tar.gz
test -d ../subsurface-"$VERSION"
test -d "$SRCDIR"/subsurface-debian/"$BRANCH"/"$RELEASE"/debian

cp -va ../subsurface_"$VERSION".orig.tar.gz ../subsurface-"$VERSION" .
cp -va "$SRCDIR"/subsurface-debian/"$BRANCH"/"$RELEASE"/debian subsurface-"$VERSION"
dpkg-source -b subsurface-"$VERSION"
