#!/bin/bash

set -e

SRCDIR=~/src

VERSION=5.0.1
BRANCH=v$VERSION

pushd "$SRCDIR"/subsurface.git
git fetch
git checkout "$BRANCH"
git submodule update
popd

pushd "$SRCDIR"/googlemaps.git
git fetch
git checkout origin/master
popd

pushd "$SRCDIR"/qtlocation.git
git fetch
git checkout origin/dev
popd

test ! -e subsurface-"$VERSION"
mkdir subsurface-"$VERSION"

cp -va "$SRCDIR"/subsurface.git/. subsurface-"$VERSION"
cp -va "$SRCDIR"/googlemaps.git subsurface-"$VERSION"/googlemaps
cp -va "$SRCDIR"/qtlocation.git subsurface-"$VERSION"/qtlocation
tar -czf subsurface_"$VERSION".orig.tar.gz subsurface-"$VERSION"
