#!/bin/bash

set -e

VERSION=5.0.2

BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/subsurface-debian
RELEASES='sid,sid bullseye,deb11u1 buster,deb10u1'
ARCHS='amd64 i386'

test -n "$SUBSURFACE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

OUTPUT_DIR="$BUILDDIR/artefacts.$$"
mkdir artefacts.$$
test -d "$OUTPUT_DIR"

cd build.$$

BRANCH=v$VERSION
GITDIR="$SUBSURFACE_DEBIAN_SRCDIR/$VERSION"

test -d "$GITDIR"

export VERSION
export BRANCH
export GITDIR

if ! "$GITDIR"/create-source-package; then
	cd ..
	rm -rf build.$$
	exit
fi

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	export RELEASE
	export REL_CODE
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$GITDIR"/create-debian-build
	for ARCH in $ARCHS; do
		sudo cowbuilder --build --buildplace ~/var/cache/pbuilder/build --buildresult "$OUTPUT_DIR" --basepath ~/var/cache/pbuilder/base-"$RELEASE"-"$ARCH".cow --aptcache ~/var/cache/aptcache subsurface_"$VERSION"-1+"$REL_CODE".dsc
		reprepro -Vb "$REPO" -C main includedeb "$RELEASE" "$OUTPUT_DIR"/subsurface_"$VERSION"-1+"$REL_CODE"_"$ARCH".deb
		reprepro -Vb "$REPO" -C main includedeb "$RELEASE" "$OUTPUT_DIR"/subsurface-dbgsym_"$VERSION"-1+"$REL_CODE"_"$ARCH".deb
	done
	reprepro -Vb "$REPO" -C main includedsc "$RELEASE" "$OUTPUT_DIR"/subsurface_"$VERSION"-1+"$REL_CODE".dsc
	cd ..
done

cd ..
rm -rf build.$$
rm -rf "$OUTPUT_DIR"
