#!/bin/bash

set -e

test -n "$RELEASE"
test -n "$REL_CODE"
test -n "$SUBSURFACE_DEBIAN_SRCDIR"
test -n "$VERSION"
test -n "$BRANCH"

test -f ../subsurface_"$VERSION".orig.tar.gz
test -d ../subsurface-"$VERSION"
test -d "$GITDIR"/"$RELEASE"/debian

cp -va ../subsurface_"$VERSION".orig.tar.gz ../subsurface-"$VERSION" .
cp -va "$GITDIR"/"$RELEASE"/debian subsurface-"$VERSION"
cd subsurface-"$VERSION"
if test -f debian/changelog; then
	exit 1
else
	dch -v "$VERSION"-1+"$REL_CODE" --create -D "$RELEASE" --package subsurface "Release $VERSION"
	cp -va debian/changelog "$GITDIR"/"$RELEASE"/debian
fi
cd ..
dpkg-source -b subsurface-"$VERSION"
