#!/bin/bash

set -e
set -x

LAST_BUILD_ID=~/.sub.last.build.id
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/subsurface
RELEASES='forky,~bpo14+1 sid, trixie,~bpo13+1 bookworm,~bpo12+1 bullseye,~bpo11+1'

test -n "$SUBSURFACE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

cd build.$$

export VERSION=$(date +%Y%m%d%H%M)

export LAST_BUILD_ID
export THIS_BUILD_ID="$LAST_BUILD_ID.new"

set +e
"$SUBSURFACE_DEBIAN_SRCDIR"/beta/create-source-package
CODE=$?
set -e

if test "$CODE" -ne 0; then
	cd ..
	rm -rf build.$$
	if test "$CODE" -eq 42; then
		exit 0
	fi
	exit "$CODE"
fi

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-1"$REL_CODE"
	export RELEASE
	export REL_CODE
	export FULL_VER
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$SUBSURFACE_DEBIAN_SRCDIR"/beta/create-debian-build
	debsign subsurface-beta_"$FULL_VER".dsc
	reprepro -Vb "$REPO" -C main includedsc "$RELEASE" subsurface-beta_"$FULL_VER".dsc

	if test -d ~/var/src-build-q; then
		mkdir -p ~/var/src-build-q/"$RELEASE"
		echo https://subsurface.dfx.at/pool/main/s/subsurface-beta/subsurface-beta_"$FULL_VER".dsc > ~/var/src-build-q/"$RELEASE"/.subsurface-beta.$$ || true
		mv ~/var/src-build-q/"$RELEASE"/.subsurface-beta.$$ ~/var/src-build-q/"$RELEASE"/subsurface-beta || true
	fi
	cd ..
done

cd ..
rm -rf build.$$

mv -f "$THIS_BUILD_ID" "$LAST_BUILD_ID"

exit 0
