#!/bin/bash

set -e
set -x

LAST_BUILD_ID=~/.sub.last.build.id
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/subsurface-debian
RELEASES='sid, bullseye,~bpo11+1 buster,~bpo10+1'
ARCHS='amd64 i386'

test -n "$SUBSURFACE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

OUTPUT_DIR="$BUILDDIR/artefacts.$$"
mkdir artefacts.$$
test -d "$OUTPUT_DIR"

cd build.$$

export VERSION=$(date +%Y%m%d%H%M)

export LAST_BUILD_ID
export THIS_BUILD_ID="$LAST_BUILD_ID.new"
if ! "$SUBSURFACE_DEBIAN_SRCDIR"/beta/create-source-package; then
	cd ..
	rm -rf build.$$
	exit
fi

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-1"$REL_CODE"
	export RELEASE
	export REL_CODE
	export FULL_VER
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$SUBSURFACE_DEBIAN_SRCDIR"/beta/create-debian-build
	for ARCH in $ARCHS; do
		sudo cowbuilder --build --buildplace ~/var/cache/pbuilder/build --buildresult "$OUTPUT_DIR" --basepath ~/var/cache/pbuilder/base-"$RELEASE"-"$ARCH".cow --aptcache ~/var/cache/aptcache subsurface-beta_"$FULL_VER".dsc
		reprepro -Vb "$REPO" -C main includedeb "$RELEASE" "$OUTPUT_DIR"/subsurface-beta_"$FULL_VER"_"$ARCH".deb
		reprepro -Vb "$REPO" -C main includedeb "$RELEASE" "$OUTPUT_DIR"/subsurface-beta-dbgsym_"$FULL_VER"_"$ARCH".deb
	done
	reprepro -Vb "$REPO" -C main includedsc "$RELEASE" "$OUTPUT_DIR"/subsurface-beta_"$FULL_VER".dsc
	cd ..
done

cd ..
rm -rf build.$$
rm -rf "$OUTPUT_DIR"

mv -f "$THIS_BUILD_ID" "$LAST_BUILD_ID"
