#!/bin/bash

set -e
set -x

PACKAGE=subsurface-beta
BRANCH=beta

test -n "$RELEASE"
test -n "$SUBSURFACE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

test -f ../"$PACKAGE"_"$VERSION".orig.tar.gz
test -d ../"$PACKAGE"-"$VERSION"
test -d "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian

cp -va ../"$PACKAGE"_"$VERSION".orig.tar.gz ../"$PACKAGE"-"$VERSION" .
cp -va "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian "$PACKAGE"-"$VERSION"
cd "$PACKAGE"-"$VERSION"
dch -v "$FULL_VER" --create -D "$RELEASE" --force-distribution --package "$PACKAGE" "Beta build"
cd ..
dpkg-source -b "$PACKAGE"-"$VERSION"
