#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$SUBSURFACE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

BRANCH=beta

test -f ../subsurface-beta_"$VERSION".orig.tar.gz
test -d ../subsurface-beta-"$VERSION"
test -d "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian

cp -va ../subsurface-beta_"$VERSION".orig.tar.gz ../subsurface-beta-"$VERSION" .
cp -va "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian subsurface-beta-"$VERSION"
cd subsurface-beta-"$VERSION"
dch -v "$FULL_VER" --create -D "$RELEASE" --package subsurface-beta "Beta build"
cd ..
dpkg-source -b subsurface-beta-"$VERSION"
