#!/bin/bash

set -e
set -x

if test -z "$VERSION"; then
	VERSION=$(date +%Y%m%d%H%M)
fi

git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/subsurface.git

cd subsurface
git tag --list v\* > ~/.sub.tags.$$
cd ..
mv -f ~/.sub.tags.$$ ~/.sub.tags.new

if test -n "$THIS_BUILD_ID"; then
	cd subsurface

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	cd ..
fi

git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/googlemaps.git

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
pushd qtlocation
git checkout 4b42b88f6b
popd

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtpositioning.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtpositioning.git
pushd qtpositioning
git checkout cfa650683e
popd

test ! -e subsurface-beta-"$VERSION"
mkdir subsurface-beta-"$VERSION"

cp -va subsurface/. subsurface-beta-"$VERSION"
cp -va googlemaps subsurface-beta-"$VERSION"/googlemaps
cp -va qtlocation subsurface-beta-"$VERSION"/qtlocation
cp -va qtpositioning subsurface-beta-"$VERSION"/qtpositioning
tar -czf subsurface-beta_"$VERSION".orig.tar.gz subsurface-beta-"$VERSION"
rm -rf subsurface googlemaps qtlocation qtpositioning

echo export VERSION="$VERSION"
