#!/bin/bash

set -e

test -n "$RELEASE"
test -n "$REL_CODE"
test -n "$SUBSURFACE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)

BRANCH=beta

test -f ../subsurface-beta_"$VERSION".orig.tar.gz
test -d ../subsurface-beta-"$VERSION"
test -d "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian

cp -va ../subsurface-beta_"$VERSION".orig.tar.gz ../subsurface-beta-"$VERSION" .
cp -va "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian subsurface-beta-"$VERSION"
cd subsurface-beta-"$VERSION"
dch -v "$VERSION"-1+"$REL_CODE" --create -D "$RELEASE" --package subsurface-beta "Beta build"
cd ..
dpkg-source -b subsurface-beta-"$VERSION"
