#!/bin/bash

set -e
set -x

if test -z "$VERSION"; then
	VERSION=$(date +%Y%m%d%H%M)
fi

git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/subsurface.git

pushd subsurface
git tag --list v\* > ~/.sub.tags.$$
popd
mv -f ~/.sub.tags.$$ ~/.sub.tags.new

if test -n "$THIS_BUILD_ID"; then
	pushd subsurface

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	popd
fi

pushd subsurface
./scripts/get-version.sh 1 > .latest-subsurface-buildnumber
mv -f .latest-subsurface-buildnumber latest-subsurface-buildnumber
echo dfx > latest-subsurface-buildnumber-extension
popd

git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/googlemaps.git googlemaps-ssrf
rm -rf googlemaps-ssrf/.git

git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/vladest/googlemaps.git googlemaps-qt6
rm -rf googlemaps-qt6/.git

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
pushd qtlocation
git checkout 4b42b88f6b
rm -rf .git
popd

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git qtlocation-qt6
pushd qtlocation-qt6
git checkout f32bfdb888
rm -rf .git
popd

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtpositioning.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtpositioning.git
pushd qtpositioning
git checkout cfa650683e
rm -rf .git
popd

git clone https://github.com/cschramm/irda.git
test -d irda

test ! -e subsurface-beta-"$VERSION"
mkdir subsurface-beta-"$VERSION"

rm -rf subsurface/.github
rm -rf subsurface/.git
rm -rf subsurface/libdivecomputer/.github
rm -rf subsurface/libdivecomputer/.git
rm -rf qtlocation/.git
rm -rf qtlocation-qt6/.git
rm -rf qtpositioning/.git
rm -rf irda/.git

cp -va subsurface/. subsurface-beta-"$VERSION"
cp -va googlemaps-ssrf subsurface-beta-"$VERSION"/googlemaps-ssrf
cp -va googlemaps-qt6 subsurface-beta-"$VERSION"/googlemaps-qt6
cp -va qtlocation subsurface-beta-"$VERSION"/qtlocation
cp -va qtlocation-qt6 subsurface-beta-"$VERSION"/qtlocation-qt6
cp -va qtpositioning subsurface-beta-"$VERSION"/qtpositioning
cp -va irda subsurface-beta-"$VERSION"/irda
tar -czf subsurface-beta_"$VERSION".orig.tar.gz subsurface-beta-"$VERSION"
rm -rf subsurface googlemaps-ssrf googlemaps-qt6 qtlocation qtlocation-qt6 qtpositioning irda

echo export VERSION="$VERSION"
