#!/bin/bash

set -e
set -x

LAST_BUILD_ID=~/.sub.last.current-qt6.build.id
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/subsurface
RELEASES='trixie,~bpo13+1'

test -n "$SUBSURFACE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

cd build.$$

export LAST_BUILD_ID
export THIS_BUILD_ID="$LAST_BUILD_ID.new"

if test -z "$BUILD"; then
	BUILD=1
fi

export REPO

set +e
"$SUBSURFACE_DEBIAN_SRCDIR"/current-qt6/create-source-package
CODE=$?
set -e

if test "$CODE" -ne 0; then
	cd ..
	rm -rf build.$$
	if test "$CODE" -eq 42; then
		exit 0
	fi
	exit "$CODE"
fi

export VERSION=$(<version)

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-"$BUILD""$REL_CODE"
	export RELEASE
	export REL_CODE
	export FULL_VER
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$SUBSURFACE_DEBIAN_SRCDIR"/current-qt6/create-debian-build
	debsign subsurface-qt6_"$FULL_VER".dsc

	if test -z "$SKIP_REPO"; then
		reprepro -Vb "$REPO" -C main includedsc "$RELEASE" subsurface-qt6_"$FULL_VER".dsc

		if test -d ~/var/src-build-q; then
			mkdir -p ~/var/src-build-q/"$RELEASE"
			echo https://subsurface.dfx.at/pool/main/s/subsurface-qt6/subsurface-qt6_"$FULL_VER".dsc > ~/var/src-build-q/"$RELEASE"/.subsurface-qt6.$$ || true
			mv ~/var/src-build-q/"$RELEASE"/.subsurface-qt6.$$ ~/var/src-build-q/"$RELEASE"/subsurface-qt6 || true
		fi
	fi

	cd ..
done

cd ..

if test -z "$SKIP_REPO"; then
	rm -rf build.$$
fi

mv -f "$THIS_BUILD_ID" "$LAST_BUILD_ID"

exit 0
