#!/bin/bash

set -e
set -x

declare -a errors

LAST_BUILD_ID=~/.sub.last.current-qt6.build.id
BUILDDIR=~/tmp
REPO=~/htdocs/dfx.at/subsurface
RELEASES='forky,~bpo14+1 sid, trixie,~bpo13+1'

test -n "$SUBSURFACE_DEBIAN_SRCDIR"

cd "$BUILDDIR"
mkdir build.$$

cd build.$$

export LAST_BUILD_ID
export THIS_BUILD_ID="$LAST_BUILD_ID.new"

set +e
"$SUBSURFACE_DEBIAN_SRCDIR"/current-qt6/create-source-package
CODE=$?
set -e

if test "$CODE" -ne 0; then
	cd ..
	rm -rf build.$$
	if test "$CODE" -eq 42; then
		exit 0
	fi
	exit "$CODE"
fi

export VERSION=$(<version)

for RELEASE in $RELEASES; do
	IFS=, read -a REL_NAMES <<< "$RELEASE"
	RELEASE=${REL_NAMES[0]}
	REL_CODE=${REL_NAMES[1]}
	FULL_VER="$VERSION"-1"$REL_CODE"
	export RELEASE
	export REL_CODE
	export FULL_VER
	mkdir "$RELEASE"
	cd "$RELEASE"
	"$SUBSURFACE_DEBIAN_SRCDIR"/current-qt6/create-debian-build
	debsign subsurface-qt6_"$FULL_VER".dsc
	reprepro -Vb "$REPO" -C main includedsc "$RELEASE" subsurface-qt6_"$FULL_VER".dsc

	if test -d ~/var/src-build-q; then
		echo https://subsurface.dfx.at/pool/main/s/subsurface/subsurface-qt6_"$FULL_VER".dsc > ~/var/src-build-q/.subsurface-qt6."$RELEASE".$$ || true
		mv ~/var/src-build-q/.subsurface-qt6."$RELEASE".$$ ~/var/src-build-q/subsurface-qt6."$RELEASE" || true
	fi
	cd ..
done

cd ..
rm -rf build.$$

mv -f "$THIS_BUILD_ID" "$LAST_BUILD_ID"

if test ${#errors[@]} -gt 0; then
	echo errors:
	echo "${errors[@]}"
	exit 1
fi

exit 0
