#!/bin/bash

set -e
set -x

test -n "$RELEASE"
test -n "$SUBSURFACE_DEBIAN_SRCDIR"
test -n "$VERSION" # VERSION=$(date +%Y%m%d%H%H)
test -n "$FULL_VER"

BRANCH=current-qt6

test -f ../subsurface-qt6_"$VERSION".orig.tar.gz
test -d ../subsurface-qt6-"$VERSION"
test -d "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian

cp -va ../subsurface-qt6_"$VERSION".orig.tar.gz ../subsurface-qt6-"$VERSION" .
cp -va "$SUBSURFACE_DEBIAN_SRCDIR"/"$BRANCH"/"$RELEASE"/debian subsurface-qt6-"$VERSION"
cd subsurface-qt6-"$VERSION"
dch -v "$FULL_VER" --create -D "$RELEASE" --force-distribution --package subsurface-qt6 "Current build"
cd ..
dpkg-source -b subsurface-qt6-"$VERSION"
