#!/bin/bash

set -e
set -x

git clone --branch current --single-branch --recurse-submodules --shallow-submodules https://github.com/subsurface/subsurface.git

if test -n "$THIS_BUILD_ID"; then
	pushd subsurface

	THIS_ID=$(git rev-parse HEAD)
	if test -n "$LAST_BUILD_ID" -a -f "$LAST_BUILD_ID"; then
		LAST_ID=$(<"$LAST_BUILD_ID")
		if test "$LAST_ID" = "$THIS_ID"; then
			echo no new commits
			exit 42
		fi
	fi

	echo "$THIS_ID" > "$THIS_BUILD_ID"
	popd
fi

COMMIT=$(<"$THIS_BUILD_ID")

pushd subsurface
./scripts/get-version.sh 1 > .latest-subsurface-buildnumber
mv -f .latest-subsurface-buildnumber latest-subsurface-buildnumber
echo dfx > latest-subsurface-buildnumber-extension
VERSION=$(scripts/get-version.sh)
popd

COMMIT_SHORT=${COMMIT:0:8}
VERSION="$VERSION"~"$COMMIT_SHORT"

echo "$VERSION" > version
echo export VERSION="$VERSION"

if test -n "$REPO" -a -z "$REBUILD"; then
	ORIG="$REPO"/pool/main/s/subsurface/subsurface-qt6_"$VERSION".orig.tar.gz
	if test -f "$ORIG"; then
		cp -v "$ORIG" .
		tar -xzf subsurface-qt6_"$VERSION".orig.tar.gz
		exit 0
	fi
fi

git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/vladest/googlemaps.git
rm -rf googlemaps/.git

#git clone --depth 1 --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
git clone --single-branch --recurse-submodules --shallow-submodules https://github.com/qt/qtlocation.git
pushd qtlocation
git checkout f32bfdb888
rm -rf .git
popd

git clone https://github.com/cschramm/irda.git
test -d irda

test ! -e subsurface-qt6-"$VERSION"
mkdir subsurface-qt6-"$VERSION"

rm -rf subsurface/.github
rm -rf subsurface/.git
rm -rf subsurface/libdivecomputer/.github
rm -rf subsurface/libdivecomputer/.git
rm -rf qtlocation/.git
rm -rf irda/.git
 
cp -va subsurface/. subsurface-qt6-"$VERSION"
cp -va googlemaps subsurface-qt6-"$VERSION"/googlemaps
cp -va qtlocation subsurface-qt6-"$VERSION"/qtlocation
cp -va irda subsurface-qt6-"$VERSION"/irda
tar -czf subsurface-qt6_"$VERSION".orig.tar.gz subsurface-qt6-"$VERSION"
rm -rf subsurface googlemaps qtlocation irda
